- name: demo on  task level variables  # only task level will have priority over play level variables
  hosts: localhost # local host is where ansible is running
  connection: local # it will not ask for username and password
  vars:
      course: "ansible"
      trainer: "siva kumar"
      duration: "150 hours"
  tasks:
  - name: print infirmation 
    vars:
        course: "devsecops with AI Ops"
    debug:
      msg: " Hi, I am learning {{ course }}, trainer is {{ trainer}}, duration is {{ duration }}"