- name: demo on promt
  hosts: localhost
  connection: local
  vars_prompt:
   - name: username
     prompt: What is your username?
     private: false   # by default it will not display username, now by using private=false it will display username

   - name: password
     prompt: please enter password
     private: true 

     tasks:
      - name: printr information
        debug:
          msg: " username is: {{ username}}, password is: {{ password}}"