- name: demo on promt
  hosts: local
  connection: local
  vars_prompt:
   - name: username
     prompt: "please enter username"
     private: false   # by default it will not display username, now by using private=false it will display username

   - name: password
     prompt: "please enter password"
     private: true   # by default it will not display password, now by using private=true it will not display password 

  tasks:
      - name: printr information
  debug:
           msg: " Username is: {{ username}}, password is: {{ password}}"