- name: inventory variables
  hosts: frontend
  become: yes
  #connection: localhost
  vars_files:
      - course.yaml
  tasks:
    - name: print information
      debug:
        msg: " Hi, I am learning {{ course }}, trainer is {{ trainer}}, duration is {{ duration }}"