- name: inventory variables
  hosts: localhost
  connection: localhost
  tasks:
    - name: print information
      debug:
        msg: " Hi, I am learning {{ course }}, trainer is {{ trainer}}, duration is {{ duration }}"