- name: demo on preference vars
  hosts: localhost
  connection: localhost
  vars:
     full_name: " siva from play level "
  vars_files:
         - course.yaml
  vars_promt:
   - name: full_name
     prompt: "please enter your full_name"
     private: false
  tasks:
     full_name: " siva from task level "
  debug:
     msg: " hi, {{ full_name}}"