- name: demo on preference vars
  hosts: frontend
  
  vars:
     full_name: " siva from play level "
  vars_files:
         - course.yaml
  vars_prompt:
   - name: full_nmae
     prompt: "please enter full_name"
     private: false
  tasks:
     full_name: " siva from task level "
  debug:
    msg: " Hi {{ full_name}}"


    # 1. CMD args
    #2. vars
    #3. vars_files
    #4. vars_prompt
    #5. play level
    #6.inventory level