- name: demo on preference vars
  hosts: localhost
  connection: localhost
  vars:
     full_name: " siva from play level "
  vars_files:
         - course.yaml
  vars_prompt:
   - name: full_nmae
     prompt: "please enter full_name"
     private: false
  tasks:
     full_name: " siva from task level "
  debug:
       msg: " hi, full name is  {{ full_name}}"