- name: course information
  hosts: localhost
  connection: localhost
  vars:
    course: "devsecops with ai ops"  # string
    duration: 150  # integer / number
    is_live_session: true # boolean
    topics: 
       - linux
       - shell
       - ansible
    more_details:
        months: "5"
        trainer: "sivakumar"
  tasks:
     - name: print information
       debug:
         msg: |
              name {{ course}}
              duration {{ duration}}
              is_live_session {{ is_live_session}}
              topics {{ topics}}