- name: demo on loops
  hosts: localhost
  tasks:
    - name: Print items in a loop
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - one
        - two
        - three
