- name: demo on filter
  hosts: localhost
  connection: localhost
  vars:
    topics: linux, shell, ansible, terraform 
    tagmap:
     name: Ansible
     project: roboshop
     environment: dev
  tasks:
   - name: convert string to list
     debug:
       msg: "{{ topics | split (',')}}"
   - name: convert map to list
     debug:
       msg: "{{tagmap | dict2items }}"
