- name: demo on error handling
  hosts: localhost
  connection: localhost
  tesks:
   - name : check roboshop user exist or not
     command: id roboshop
     register: users_output
     ignore_errors: true

   - name: print user output
     debug:
       msg: "{{ users_output }}"
