- name: demo on error handling
  hosts: localhost
  connection: localhost
  become: yes
  tasks:
   - name : check roboshop user exist or not
     command: id roboshop
     register: users_output
     ignore_errors: true

   - name: print user output
     debug:
       msg: "{{ users_output }}"

   - name: create user
     command : useradd roboshop
     when: users_output.rc != 0
