[frontend] # we can add 500 servers also here, so that ansible will conect to all 500 servers 
172.31.46.50 course="Ansible for node-1"  # these are called as individual host variables
172.31.36.209 course="Ansible for node-2" 
    
[catalogue ]
172.31.10.8

[user]
172.31.10.9


[cart]
172.31.10.10

[backend]
172.31.20.5

[db]  # this is called group
172.31.30.11

[ localhost ]
localhost

; local group vars # this is group of localhost, so we can give variables to all the servers in localhost group
[ local:vars ]
course="ansible"     # these are called group varibles
trainer="siva kumar"
duration=" 15 hours "

[ frontend:vars ]
course="Devops AI"
trainer=" Bobby"
duration=" 150 hours"

# if roboshop servers are running on RHEL(red hat enterprise linus)
# if there is some problem in RHEL
# then if we give like this hosts: roboshop , then hosts will go and search with roboshop and che
# and check for the roboshop children and after finding it will take the ip's of frontend, catalogue, user, cart, backend and db 
# and then it will connect to all the servers and do the work
# all the groups are children of roboshop

[roboshop:children]  # this is called group of groups (parent group) 
frontend
catalogue
user
cart
backend
db


