- name: roboshop instance management
  hosts: local
  connection: local # aws configure for user authentication
  vars:
    instances: [ "mongodb" , " redis" , "mysql" , "rabbitmq"]
    image_id: ami-0220d79f3f480ecf5
  tasks:
   - name: create ec2 instances
      amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: " roboshop-{{item}} "
      security_groups: 
      - "roboshsop-{{item}}"
      - "roboshop-common"
      image_id: ami-0220d79f3f480ecf5
 loop: " {{ instances}}"
 register: ec2_output

#- name: print output
 #  debug:
 #   msg: "{{ ec2-output}}"

- name: create route53 records
  debug:
    msg: "Instance name : {{ item.item }}"
  loop: "{{ ec2-output.results }}"

    
